### ISSUE TITLE
关于 subhd 搜索频率的限制

### ISSUE THREAD

**Issue by allanpk716** [allanpk716/ChineseSubFinder#12]
如题，目前查看日志发现搜索的瓶颈再此。虽然进行了简单的循环处理，但是依然是个问题。这样并发处理就意义不大了，但是不并发资源多了就很慢。

目前想到的是：

1. 加入多个代理，去分担查询压力。缺点，但是毕竟不是每个人都有多个代理可用
2. 做一个类似 shooter 字幕查询接口，将 zimuku 和 subhd 的结果缓存下来。缺点，貌似字幕涉及版权，风险较大。

欢迎讨论。

**Comment by mhqschen** [comment]
第一个对普通用户来说实操太难了。第二个是缓存到客户端？

**Comment by allanpk716** [comment]
> 第一个对普通用户来说实操太难了。第二个是缓存到客户端？

第二个，粗暴点就是缓存到服务器，然后做静态文件走 CDN 加速。
这样就不用大家重复去字幕网站查询，效率低。
或者是其他的网络文件分享。主要问题应该是法律风险。

**Comment by allanpk716** [comment]
还有个办法，允许本程序开出一个额外的辅助功能，上传本机下载的字幕到 opensubtitles 上，配置类似：
```
AllowShared2Opensubtitles: true
Opensubtitles:
         User: abc
         Pwd: 123
```
然后其他本程序用户如果也填写了 opensubtitles  的账号密码，就会优先去上面找字幕。同时如果其他人用的 Emby 类似的软件就能从 opensubtitles  获取相应的字幕（有待评估）

1. opensubtitles  上传、下载字幕的功能需要看一下
2. 如果多人上传相同的字幕会有什么影响，这个需要评估，或者说要限制和区分
3. 上传完的字幕要怎么能够比较准确的获取到？
