### ISSUE TITLE
程序无法正常启动

### ISSUE THREAD

**Issue by willyautoman** [allanpk716/ChineseSubFinder#257]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.21.1

> 环境: docker 

## 你遇到什么问题了？

>程序无法启动，或者启动后十秒内自动重启，如果不开代理，显示无法连通谷歌，如果开了代理就在频繁报错

## 你的问题弄重现嘛？

> 能够重现

## 你期望的结果

> 能正常使用，或者添加socks5 代理

## 给出当前程序的配置文件

```json
{
    "user_info": {
        "username": "",
        "password": ""
    },
    "common_settings": {
        "scan_interval": "12h",
        "threads": 4,
        "run_scan_at_start_up": true,
        "movie_paths": ["/media/medias"],
        "series_paths": ["/media/medias"]
    },
    "advanced_settings": {
        "proxy_settings": {
            "use_http_proxy": true,
            "http_proxy_address": "http://127.0.0.1:1081"
        },
        "debug_mode": false,
        "save_full_season_tmp_subtitles": true,
        "sub_type_priority": 0,
        "sub_name_formatter": 1,
        "save_multi_sub": false,
        "custom_video_exts": [],
        "fix_time_line": true,
        "topic": 1
    },
    "emby_settings": {
        "enable": false,
        "address_url": "",
        "api_key": "",
        "max_request_video_number": 500,
        "skip_watched": false,
        "movie_paths_mapping": {
            "/media/medias": ""
        },
        "series_paths_mapping": {
            "/media/medias": ""
        }
    },
    "developer_settings": {
        "enable": false,
        "bark_server_address": ""
    },
    "timeline_fixer_settings": {
        "max_offset_time": 120,
        "min_offset": 0.1
    },
    "experimental_function": {
        "auto_change_sub_encode": {
            "enable": false,
            "des_encode_type": 0
        }
    }
}

```

## 如果是使用 Docker，请给出对应的配置信息

```yml
version: "3"
services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    container_name: subfinder
    volumes:
      - /data/chinesesubfinder/cache:/app/cache
      - /data/chinesesubfinder/config:/config

      - /data/qb/downloads/meidas:/media
    ports:
      - "19035:19035"
    environment:
      - PUID=1026
      - PGID=1026
      - TZ=Asia/Shanghai
    network_mode: "host"
    restart: unless-stopped
```
## 请给出当次问题的完整日志
报错具体内容详见 ：https://paste.ubuntu.com.cn/4545651
