### ISSUE TITLE
Chrome执行文件错误？

### ISSUE THREAD

**Issue by so1ar** [allanpk716/ChineseSubFinder#292]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.24.2
>
> 环境: docker，树莓派4B，ARM64系统。
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> subhd下载字幕失败，查看日志发现有类似 `[ERROR]: 2022-04-06 18:45:11 - Queue 0 subhd oneMovieDlSubInOneSite fork/exec /root/.cache/rod/browser/chromium-901912/chrome-linux/chrome: exec format error` 的错误，我不太懂go-rod，但我记得谷歌官方的闭源Chrome是不提供arm版本的，只有开源的chromium才有arm版本，不知道是不是这个原因。

## 你的问题弄重现嘛？

> 能够重现

## 你期望的结果

> subhd可以正常下载字幕

## 给出当前程序的配置文件

```json
{
    "user_info":{
        "username":"",
        "password":""
    },
    "common_settings":{
        "scan_interval":"6h",
        "threads":1,
        "run_scan_at_start_up":true,
        "movie_paths":[
            "/media/movie"
        ],
        "series_paths":[
            "/media/TV"
        ]
    },
    "advanced_settings":{
        "proxy_settings":{
            "use_http_proxy":false,
            "http_proxy_address":""
        },
        "debug_mode":false,
        "save_full_season_tmp_subtitles":false,
        "sub_type_priority":0,
        "sub_name_formatter":1,
        "save_multi_sub":false,
        "custom_video_exts":[

        ],
        "fix_time_line":false,
        "topic":1
    },
    "emby_settings":{
        "enable":false,
        "address_url":"",
        "api_key":"",
        "max_request_video_number":500,
        "skip_watched":false,
        "movie_paths_mapping":{
            "/media/movie":""
        },
        "series_paths_mapping":{
            "/media/TV":""
        }
    },
    "developer_settings":{
        "enable":false,
        "bark_server_address":""
    },
    "timeline_fixer_settings":{
        "max_offset_time":120,
        "min_offset":0.1
    },
    "experimental_function":{
        "auto_change_sub_e    ncode":{
            "enable":false,
            "des_encode_type":0
        },
        "chs_cht_changer":{
            "enable":false,
            "des_chinese_language_type":0
        },
        "remote_chrome_settings":{
            "enable":false,
            "remote_docker_url":"",
            "remote_adblock_path":"",
            "remote_user_data_dir":""
        }
    }
}
```

## 如果是使用 Docker，请给出对应的配置信息

```
version: "3"
 services:
   chinesesubfinder:
     image: allanpk716/chinesesubfinder:latest
     volumes:
       - /home/pi/sub/config/cache:/app/cache
       - /home/pi/sub/config:/config

       - //home/pi/share:/media
     network_mode: host
     environment:
       - PUID=1000
       - PGID=1000
       - TZ=Asia/Shanghai
       - PERMS=true
     restart: unless-stopped
```

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。
[2022-04-06 18 35 16.log](https://github.com/allanpk716/ChineseSubFinder/files/8426996/2022-04-06.18.35.16.log)
