### ISSUE TITLE
`proxyAddressValidHttpFormat` not working for docker user

### ISSUE THREAD

**Issue by Trim21** [allanpk716/ChineseSubFinder#303]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.25.0
>
> 环境: docker
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

我的代理客户端是运行在另一个docker里，然后两个container使用docker 的 network功能链接起来的。
所以我的代理链接是 `http://clash:7890`

但是现在的正则认为这是一个错误的代理网址 https://github.com/allanpk716/ChineseSubFinder/blob/d5cbd8fbbe52335d1f35e81dbb79839be00e6ea5/internal/pkg/url_connectedness_helper/url_connectedness_helper.go#L63-L71

```text
[info]: 2022-04-17 20:41:06 - UseHttpProxy: http://clash:7890
[error]: 2022-04-17 20:41:06 - UrlConnectednessTest Target Site https://google.com, proxy address illegal, only support http://xx:xx
```

## 你的问题弄重现嘛？

能

## 你期望的结果

应该正确连接到代理

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
  "advanced_settings": {
    "proxy_settings": {
      "use_http_proxy": true,
      "http_proxy_address": "http://clash:7890"
    }
  }
}
```

## 如果是使用 Docker，请给出对应的配置信息

```yaml
version: '3.7'
services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:v0.25.0
    networks:
      - backends
    ports:
      - '19035:19035'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    restart: unless-stopped
  clash:
    image: dreamacro/clash:latest
    networks: [backends]
    expose:
      - 7890
      - 7891
    ports:
      - "8080:8080" # external controller (Restful API)
      - "7890:7890"
      - "7891:7891"
    restart: unless-stopped

networks:
  backends:
```

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中
