### ISSUE TITLE
Emby API 高级功能，过滤点已经播放过的视频，不进行字幕下载

### ISSUE THREAD

**Issue by allanpk716** [allanpk716/ChineseSubFinder#35]
如题，为了提高搜索的效率，目前已经实现了 Emby API 的高级功能，可以更快的获取“最近”加入的视频列表。

## 新增 UserId 字段配置

再此基础上，可以进一步的提高搜索的效率，比如：

```
EmbyConfig:
    Url: http://192.168.50.x:8096
    ApiKey: 123456789
    UserId: abc123456  # 新增 UserId 信息
    LimitCount: 500
```

考虑新增 UserId 信息，即可拿到该用户的视频播放信息，比如你一共有10个视频最近下载的，有5个你已经看过了（"Played": true），那么就跳过这些播放过的视频，无需进行视频字幕的搜索。从而提高搜索下载的效率。

如果 UserId 这个字段不填写，默认就是空，那么就默认播放与未播放的视频都进行为期三个月的搜索逻辑。见  [如何判断视频是否需要下载、更新字幕的](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%A6%82%E4%BD%95%E5%88%A4%E6%96%AD%E8%A7%86%E9%A2%91%E6%98%AF%E5%90%A6%E9%9C%80%E8%A6%81%E4%B8%8B%E8%BD%BD%E3%80%81%E6%9B%B4%E6%96%B0%E5%AD%97%E5%B9%95%E7%9A%84.md)

## 如何获取 UserId 信息

<img width="1266" alt="获取 UserID 00" src="https://user-images.githubusercontent.com/1176000/127109268-47ad1917-bb07-492b-8153-5fa3479167d4.png">

<img width="619" alt="获取 UserID 01" src="https://user-images.githubusercontent.com/1176000/127109280-2d570727-b94a-4ae8-a30c-aface135d16e.png">

<img width="749" alt="获取 UserID 02" src="https://user-images.githubusercontent.com/1176000/127109440-4bd8ee18-8896-4950-9a19-dde05979b4f8.png">
