### ISSUE TITLE
v0.13.x 版本说明以及建议

### ISSUE THREAD

**Issue by allanpk716** [allanpk716/ChineseSubFinder#42]
## Emby API 高级设置再次提速
在 v0.12.x 基础上，支持了 Emby 每个用户观看视频记录的查询，也就是可以做到，只要你的 Emby 服务器上任意一个人看过一部视频，就可以排除这个视频继续去搜索字幕。

使用的是 SkipWatched 字段控制，开启后，搜索效率会更高。文档见：[高阶设置 - Emby API 支持](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%AB%98%E9%98%B6%E8%AE%BE%E7%BD%AE%20-%20Emby%20API%20%E6%94%AF%E6%8C%81.md)

```
EmbyConfig:
    Url: http://192.168.50.x:8096
    ApiKey: 123456789
    LimitCount: 3000
    SkipWatched: false
```

## 修复 ass 字幕识别问题
同时修复了 ass 字幕某些情况下识别字幕语言类型错误的问题，这个问题可以直接导致视频字幕无法正确下载。
